# Generated by Django 4.1.1 on 2022-09-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customerorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='customerorder',
            old_name='customer_id',
            new_name='website_customer',
        ),
    ]
