# Generated by Django 4.1.1 on 2022-09-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_product_id_customerorder_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='sum_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
