# Generated by Django 4.1.1 on 2022-10-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customerorder_quantity_customerorder_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
