# Generated by Django 4.1.1 on 2022-10-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_reservations_remove_orderproducts_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='number_of_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
